--liquibase formatted sql

--changeset dev-kot:prog_ver_1 dbms:oracle
CREATE SEQUENCE S_STUDENT;

CREATE TABLE STUDENT(
  ID              INTEGER            NOT NULL,
  NAME            VARCHAR2(45),
  CONSTRAINT PK_STUDENT PRIMARY KEY (ID)
);

--rollback DROP TABLE STUDENT;
--rollback DROP SEQUENCE S_STUDENT;


--changeset dev-kot:prog_ver_2 dbms:oracle
CREATE SEQUENCE S_COURSE;

CREATE TABLE COURSE(
  ID              INTEGER            NOT NULL,
  NAME            VARCHAR2(45),
  CONSTRAINT PK_COURSE PRIMARY KEY (ID)
);

ALTER TABLE STUDENT ADD ID_COURSE INTEGER;
ALTER TABLE STUDENT ADD CONSTRAINT FK_PK_ID_COURSE_ID_STUDENT FOREIGN KEY (ID_COURSE) REFERENCES COURSE (ID);

--rollback ALTER TABLE STUDENT DROP CONSTRAINT FK_PK_ID_COURSE_ID_STUDENT;
--rollback ALTER TABLE STUDENT DROP COLUMN ID_COURSE;
--rollback DROP TABLE COURSE;
--rollback DROP SEQUENCE S_COURSE;