
package com.services.jax_ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TemperatureBryanskService", targetNamespace = "http://jax_ws.services.com/", wsdlLocation = "http://localhost:8080/myserver/my_url_pattern?wsdl")
public class TemperatureBryanskService
    extends Service
{

    private final static URL TEMPERATUREBRYANSKSERVICE_WSDL_LOCATION;
    private final static WebServiceException TEMPERATUREBRYANSKSERVICE_EXCEPTION;
    private final static QName TEMPERATUREBRYANSKSERVICE_QNAME = new QName("http://jax_ws.services.com/", "TemperatureBryanskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/myserver/my_url_pattern?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEMPERATUREBRYANSKSERVICE_WSDL_LOCATION = url;
        TEMPERATUREBRYANSKSERVICE_EXCEPTION = e;
    }

    public TemperatureBryanskService() {
        super(__getWsdlLocation(), TEMPERATUREBRYANSKSERVICE_QNAME);
    }

    public TemperatureBryanskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEMPERATUREBRYANSKSERVICE_QNAME, features);
    }

    public TemperatureBryanskService(URL wsdlLocation) {
        super(wsdlLocation, TEMPERATUREBRYANSKSERVICE_QNAME);
    }

    public TemperatureBryanskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEMPERATUREBRYANSKSERVICE_QNAME, features);
    }

    public TemperatureBryanskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TemperatureBryanskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TemperatureBryansk
     */
    @WebEndpoint(name = "TemperatureBryanskPort")
    public TemperatureBryansk getTemperatureBryanskPort() {
        return super.getPort(new QName("http://jax_ws.services.com/", "TemperatureBryanskPort"), TemperatureBryansk.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TemperatureBryansk
     */
    @WebEndpoint(name = "TemperatureBryanskPort")
    public TemperatureBryansk getTemperatureBryanskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jax_ws.services.com/", "TemperatureBryanskPort"), TemperatureBryansk.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEMPERATUREBRYANSKSERVICE_EXCEPTION!= null) {
            throw TEMPERATUREBRYANSKSERVICE_EXCEPTION;
        }
        return TEMPERATUREBRYANSKSERVICE_WSDL_LOCATION;
    }

}
