
package com.services.jax_ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TemperatureBryansk", targetNamespace = "http://jax_ws.services.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TemperatureBryansk {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.services.jax_ws.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLikeBook", targetNamespace = "http://jax_ws.services.com/", className = "com.services.jax_ws.GetLikeBook")
    @ResponseWrapper(localName = "getLikeBookResponse", targetNamespace = "http://jax_ws.services.com/", className = "com.services.jax_ws.GetLikeBookResponse")
    @Action(input = "http://jax_ws.services.com/TemperatureBryansk/getLikeBookRequest", output = "http://jax_ws.services.com/TemperatureBryansk/getLikeBookResponse")
    public Book getLikeBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemperature", targetNamespace = "http://jax_ws.services.com/", className = "com.services.jax_ws.GetTemperature")
    @ResponseWrapper(localName = "getTemperatureResponse", targetNamespace = "http://jax_ws.services.com/", className = "com.services.jax_ws.GetTemperatureResponse")
    @Action(input = "http://jax_ws.services.com/TemperatureBryansk/getTemperatureRequest", output = "http://jax_ws.services.com/TemperatureBryansk/getTemperatureResponse")
    public String getTemperature(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
